services:
  api:
    container_name: shorturl-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
